spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/order_mgt}
    username: ${DB_USERNAME:order_user}
    password: ${DB_PASSWORD:order_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: ${SERVER_PORT:8080}